Areas/CMS/Controllers/CMSUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Colmart.Model_Manager;
using Colmart.Models;
using ColmartCMS.View_Models;
using ColmartCMS.View_Models.Users;
using ColmartCMS.View_Models.CMSUsers;
using System.Drawing;
using System.IO;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using ColmartCMS.Assistant_Classes;
using Colmart;

namespace ColmartCMS.Controllers
{
    public class CMSUsersController : Controller
    {
        ColmartDBContext db = new ColmartDBContext();
        // GET: Profile
        public ActionResult CMSUserProfile()
        {
            //Redirect to login if null session exists
            if (Session["clsCMSUser"] == null)
                return RedirectToAction("Login", "Account");

            clsCMSUserProfile clsCMSUserProfile = new clsCMSUserProfile();
            clsCMSUserProfile.clsCMSUser = (clsCMSUsers)Session["clsCMSUser"];

            clsCMSUserProfile.strFullName = clsCMSUserProfile.clsCMSUser.strFirstName + " " + clsCMSUserProfile.clsCMSUser.strSurname;

            if (clsCMSUserProfile.clsCMSUser.strImagePath != null && clsCMSUserProfile.clsCMSUser.strImagePath != "" && clsCMSUserProfile.clsCMSUser.strImageName != null && clsCMSUserProfile.clsCMSUser.strImageName != "")
                clsCMSUserProfile.strFullImagePath = "/" + clsCMSUserProfile.clsCMSUser.strImagePath + "/" + clsCMSUserProfile.clsCMSUser.strImageName;

            return View(clsCMSUserProfile);
        }

        public ActionResult CMSUserProfileEdit()
        {
            //Redirect to login if null session exists
            if (Session["clsCMSUser"] == null)
                return RedirectToAction("Login", "Account");

            clsCMSUserProfileEdit clsCMSUserProfileEdit = new clsCMSUserProfileEdit();
            clsCMSUserProfileEdit.clsCMSUser = (clsCMSUsers)Session["clsCMSUser"];

            clsCMSUserProfileEdit.strEmailAddress = clsCMSUserProfileEdit.clsCMSUser.strEmailAddress;
            clsCMSUserProfileEdit.strCMSRoleType = clsCMSUserProfileEdit.clsCMSUser.clsCMSRoleType.strTitle;

            if (clsCMSUserProfileEdit.clsCMSUser.strImagePath != null && clsCMSUserProfileEdit.clsCMSUser.strImagePath != "" && clsCMSUserProfileEdit.clsCMSUser.strImageName != null && clsCMSUserProfileEdit.clsCMSUser.strImageName != "")
                clsCMSUserProfileEdit.strFullImagePath = "/" + clsCMSUserProfileEdit.clsCMSUser.strImagePath + "/" + clsCMSUserProfileEdit.clsCMSUser.strImageName;

            clsCMSRoleTypesManager clsCMSRoleTypesManager = new clsCMSRoleTypesManager();
            clsCMSUserProfileEdit.lstCMSRoleTypes = clsCMSRoleTypesManager.getAllCMSRoleTypesList();

            return View(clsCMSUserProfileEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CMSUserProfileEdit(clsCMSUserProfileEdit clsCMSUserProfileEdit)
        {
            //Redirect to login if null session exists
            if (Session["clsCMSUser"] == null)
                return RedirectToAction("Login", "Account");

            clsCMSUsers clsCMSUser = (clsCMSUsers)Session["clsCMSUser"];
            clsCMSUsersManager clsCMSUsersManager = new clsCMSUsersManager();

            string strOldPasswordCheck = "";
            if (clsCMSUserProfileEdit.strOldPassword != null && clsCMSUserProfileEdit.strOldPassword != "")
            {
                strOldPasswordCheck = clsCommonFunctions.GetMd5Sum(clsCMSUserProfileEdit.strOldPassword);
                if (clsCMSUser.strPassword != strOldPasswordCheck)
                {
                    ModelState.AddModelError("passwordError", "Incorrect Password");

                    clsCMSUserProfileEdit.clsCMSUser = (clsCMSUsers)Session["clsCMSUser"];

                    clsCMSUserProfileEdit.strEmailAddress = clsCMSUserProfileEdit.clsCMSUser.strEmailAddress;

                    if (clsCMSUserProfileEdit.clsCMSUser.strImagePath != null && clsCMSUserProfileEdit.clsCMSUser.strImagePath != "" && clsCMSUserProfileEdit.clsCMSUser.strImageName != null && clsCMSUserProfileEdit.clsCMSUser.strImageName != "")
                        clsCMSUserProfileEdit.strFullImagePath = "/" + clsCMSUserProfileEdit.clsCMSUser.strImagePath + "/" + clsCMSUserProfileEdit.clsCMSUser.strImageName;

                    clsCMSRoleTypesManager clsCMSRoleTypesManager = new clsCMSRoleTypesManager();
                    clsCMSUserProfileEdit.lstCMSRoleTypes = clsCMSRoleTypesManager.getAllCMSRoleTypesList();

                    return View(clsCMSUserProfileEdit);
                }
            }

            ModelState.AddModelError("passwordError", "");
            if (strOldPasswordCheck != "")
            {
                if (clsCMSUserProfileEdit.strNewPassword != null && clsCMSUserProfileEdit.strNewPassword != "")
                    clsCMSUser.strPassword = clsCommonFunctions.GetMd5Sum(clsCMSUserProfileEdit.strNewPassword);
                else
                    clsCMSUser.strPassword = clsCommonFunctions.GetMd5Sum(clsCMSUser.strEmailAddress);
            }

            clsCMSUser.strFirstName = clsCMSUserProfileEdit.clsCMSUser.strFirstName;
            clsCMSUser.strSurname = clsCMSUserProfileEdit.clsCMSUser.strSurname;
            clsCMSUser.strContactNumber = clsCMSUserProfileEdit.clsCMSUser.strContactNumber;
            clsCMSUser.strBiographicalInfo = clsCMSUserProfileEdit.clsCMSUser.strBiographicalInfo;
            if (clsCMSUser.clsCMSRoleType.strTitle == "Super Admin")
                clsCMSUser.iCMSRoleTypeID = clsCMSUserProfileEdit.clsCMSUser.iCMSRoleTypeID;

            //Save image
            if (clsCMSUserProfileEdit.strCropImageData != null && clsCMSUserProfileEdit.strCropImageData != "")
            {
                string data = clsCMSUserProfileEdit.strCropImageData;
                data = data.Replace("data:image/png;base64,", "");
                string strImageName = "imgProfile_" + clsCMSUserProfileEdit.clsCMSUser.strFirstName + clsCMSUserProfileEdit.clsCMSUser.strSurname + ".png";
                string strSmallImageName = "sml_imgProfile_" + clsCMSUserProfileEdit.clsCMSUser.strFirstName + clsCMSUserProfileEdit.clsCMSUser.strSurname + ".png";

                string strDestPath = "";
                if (clsCMSUser.strImagePath != null && clsCMSUser.strImagePath != "")
                {
                    strDestPath = clsCMSUser.strImagePath.Replace("/", "\\");
                }
                else
                {
                    string newPath = GetUniquePath();
                    strDestPath = "images\\cmsUsers_Images\\" + newPath;
                    clsCMSUser.strImagePath = strDestPath.Replace("\\", "/");
                }

                string strFullDestPath = AppDomain.CurrentDomain.BaseDirectory + strDestPath;
                if (!System.IO.Directory.Exists(strFullDestPath))
                {
                    System.IO.Directory.CreateDirectory(strFullDestPath);
                }
                else
                {
                    //Clear files
                    string[] strAllFilePaths = Directory.GetFiles(strFullDestPath);
                    foreach (string strFilePath in strAllFilePaths)
                        System.IO.File.Delete(strFilePath);
                }

                clsCMSUser.strImageName = strImageName;

                string strImagePath = strFullDestPath + "\\" + strImageName;
                string strSmallImagePath = strFullDestPath + "\\" + strSmallImageName;

                byte[] bytes = Convert.FromBase64String(data);

                Image image;
                using (MemoryStream ms = new MemoryStream(bytes))
                {
                    image = Image.FromStream(ms);
                }

                //Smaller Image
                Image smallImage = (Image)ResizeImage(image, 35, 35);
                //Save images
                image.Save(strImagePath, System.Drawing.Imaging.ImageFormat.Png);
                smallImage.Save(strSmallImagePath, System.Drawing.Imaging.ImageFormat.Png);
            }
            else //save default images
            {
                string strDefaultImagespath = AppDomain.CurrentDomain.BaseDirectory + "images\\defaultImages";

                string strDestPath = "";
                if (clsCMSUser.strImagePath != null && clsCMSUser.strImagePath != "")
                {
                    strDestPath = clsCMSUser.strImagePath.Replace("/", "\\");
                }
                else
                {
                    string newPath = GetUniquePath();
                    strDestPath = "images\\cmsUsers_Images\\" + newPath;
                    clsCMSUser.strImagePath = strDestPath.Replace("\\", "/");
                }

                string strFullDestPath = AppDomain.CurrentDomain.BaseDirectory + strDestPath;
                if (!System.IO.Directory.Exists(strFullDestPath))
                {
                    System.IO.Directory.CreateDirectory(strFullDestPath);
                }
                else
                {
                    //Clear files
                    string[] strAllFilePaths = Directory.GetFiles(strFullDestPath);
                    foreach (string strFilePath in strAllFilePaths)
                        System.IO.File.Delete(strFilePath);
                }

                clsCMSUser.strImageName = "default_image.png";

                string strImagePath = strFullDestPath + "\\" + "default_image.png";
                string strSmallImagePath = strFullDestPath + "\\" + "sml_default_image.png";

                //Copy small and default sizes
                System.IO.File.Copy(strDefaultImagespath + "\\default_image.png", strImagePath);
                System.IO.File.Copy(strDefaultImagespath + "\\sml_default_image.png", strSmallImagePath);
            }

            //Update CMS user
            clsCMSUsersManager.saveCMSUser(clsCMSUser);

            //Update Session

Areas/CMS/Views/CMSUsers/CMSUserAdd.cshtml
@model ColmartCMS.View_Models.CMSUsers.clsCMSUserAdd

@{
    ViewBag.Title = "CMSUserAdd";
}

@*Crop Slim Stylesheet*@
@Styles.Render("~/Content/cms/slimCropStylesheets")

<!-- start: page -->
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">CMS User</h2>
            </header>
            <div class="panel-body">
            @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "frmCMSUserAdd", @name = "frmCMSUserAdd" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <h4 class="mb-xlg">Profile Image</h4>
                        <div class="row">
                            <div class="col-md-4 col-lg-3">
                                <section class="panel">
                                        <div class="thumb-info mb-md">
                                            <div id="cropImageDiv" class="slim"
                                                 data-size="300,300"
                                                 data-ratio="1:1"
                                                 data-label="Click to Upload or Drop Image Here"
                                                 data-will-transform="getImageData">
                                                <input type="file" />
                                                <img id="imgCrop" class="rounded img-responsive" alt="Profile Image">
                                            </div>
                                        </div>
                                </section>
                            </div>
                            
                        <div class="col-md-8 col-lg-9">
                            <h4 class="mb-xlg">Personal Information</h4>
                            <fieldset>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strFirstName">First Name</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.clsCMSUser.strFirstName, new { htmlAttributes = new { @id = "strFirstName", @placeholder = "First Name", @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.clsCMSUser.strFirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strSurname">Last Name</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.clsCMSUser.strSurname, new { htmlAttributes = new { @id = "strSurname", @placeholder = "Last Name", @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.clsCMSUser.strSurname, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strEmailAddress">Email</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.clsCMSUser.strEmailAddress, new { htmlAttributes = new { @id = "strEmailAddress", @placeholder = "Email", @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.clsCMSUser.strEmailAddress, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strContactNumber">Contact Number</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.clsCMSUser.strContactNumber, new { htmlAttributes = new { @id = "strContactNumber", @placeholder = "Contact Number", @class = "form-control", @maxlength = "10" } })
                                    @Html.ValidationMessageFor(model => model.clsCMSUser.strContactNumber, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </fieldset>
                        </div>
                    </div>
                    <hr class="dotted tall">
                    <h4 class="mb-xlg">General Information</h4>
                    <fieldset>
                        <div class="form-group">
                            <label class="col-md-3 control-label" for="strBiographicalInfo">Biographical Info</label>
                            <div class="col-md-8">
                                @Html.TextAreaFor(Model => Model.clsCMSUser.strBiographicalInfo, new { @id = "strBiographicalInfo", @placeholder = "Info", @class = "form-control", @rows = "4" })
                            </div>
                        </div>
                    </fieldset>
                    @if (Model.strCMSRoleType == "Super Admin")
                    {
                        <hr class="dotted tall">
                        <h4 class="mb-xlg">Role Type</h4>
                        <fieldset>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="lstCMSRoleTypes">Role</label>
                                <div class="col-md-8">
                                    @if (Model.lstCMSRoleTypes.Count > 0)
                                    {
                                        @Html.DropDownListFor(Model => Model.clsCMSUser.iCMSRoleTypeID, new SelectList(Model.lstCMSRoleTypes, "iCMSRoleTypeID", "strTitle"), "-- Select Role Type --", new { id = "lstCMSRoleTypes", name = "lstCMSRoleTypes" })
                                        <br />
                                        @Html.ValidationMessageFor(model => model.clsCMSUser.iCMSRoleTypeID, "", new { @class = "text-danger" })
                                    }
                                    else
                                    {
                                        @Html.DropDownListFor(Model => Model.clsCMSUser.iCMSRoleTypeID, new SelectList(Model.lstCMSRoleTypes, "iCMSRoleTypeID", "strTitle"), "-- No Role Types Available --", new { id = "lstCMSRoleTypes", name = "lstCMSRoleTypes" })
                                        <br />
                                        @Html.ValidationMessageFor(model => model.clsCMSUser.iCMSRoleTypeID, "", new { @class = "text-danger" })
                                    }
                                </div>
                            </div>
                        </fieldset>
                    }
                    <hr class="dotted tall">
                    <h4 class="mb-xlg">Password</h4>
                    <fieldset class="mb-xl">
                        <div class="form-group">
                            <label class="col-md-3 control-label" for="strNewPassword"></label>
                            <div class="col-md-8">
                                <span class="icon"><i class="fa fa-info-circle"></i></span>
                                <label>If no password is specified, the user email will be used as the password</label>
                            </div>
                        </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strNewPassword">Password</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.strNewPassword, new { htmlAttributes = new { @id = "strNewPassword", @placeholder = "Password", @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.strNewPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="strConfirmPassword">Confirm Password</label>
                                <div class="col-md-8">
                                    @Html.EditorFor(Model => Model.strConfirmPassword, new { htmlAttributes = new { @id = "strConfirmPassword", @placeholder = "Confirm Password", @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.strConfirmPassword, "", new { @class = "text-danger" })
                                </div>
                            </div>
                    </fieldset>
                    <div class="row">
                        <hr />
                    </div>
                        <div class="row">
                            <div class="col-md-3">
                                <a href="@Url.Action("CMSUsersView", "CMSUsers")" class="btn btn-default">Back</a>
                                <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </div>
                    </div>
                @Html.HiddenFor(model => model.strCropImageName)
                @Html.HiddenFor(model => model.strCropImageData)
            }
                </div>
        </section>
    </div>
</div>
<!-- end: page -->

@*Crop Slim Script*@
@Scripts.Render("~/bundles/cms/slimCropScripts")

@**** CHANGE MASTER PAGE / LAYOUT PAGE HEADER (H2) TEXT AND PAGE TITLE AFTER PAGE LOADS ****@
<script type="text/javascript">
    window.onload = function ()
    {
        $("#strPageTitle").text("Add CMS User | Colmart CMS");
        $("#h2PageHeader").text("Add CMS User");

        //Update Breadcrumbs
        $("#olBreadcrumbs").append("<li><a href='@Url.Action("CMSUsersView", "CMSUsers")'>CMS Users</a></li>");
        $("#olBreadcrumbs").append("<li><span>Add CMS User</span></li>");

        //CLEAR IMAGE DATA ON DELETE
        $(".slim-btn-remove").click(function () {
            $("#strCropImageName").val(null);
            $("#strCropImageData").val(null);
        });
    }
</script>

@**** CROP IMAGE FUNCTION ****@
<script type="text/javascript">

        function getImageData(data, ready) {
            var dataString = data.output.image.toDataURL();
            $("#strCropImageName").val(data.input.name);
            $("#strCropImageData").val(dataString);
            // continue saving the data
            ready(data);
        }
</script>

Areas/CMS/Views/CMSUsers/CMSUsersView.cshtml
@model ColmartCMS.View_Models.CMSUsers.clsCMSUsersView

@{
    ViewBag.Title = "CMSUsersView";
}

@*Tables Stylesheet*@
@Styles.Render("~/Content/cms/tableStylesheets")

<!-- start: page -->
<section class="panel">
    <header class="panel-heading">
        <h2 class="panel-title">CMS Users (@Model.lstCMSUsers.Count)</h2>
    </header>
    <div class="panel-body">
        <table class="table table-bordered table-striped mb-none" id="datatable-default">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.lstCMSUsers)
                {

                    <tr data-item-id="@item.iCMSUserID" id="@item.iCMSUserID">
                        <td style="vertical-align: middle;">@item.strFirstName</td>
                        <td style="vertical-align: middle;">@item.strSurname</td>
                        <td style="vertical-align: middle;">@item.strEmailAddress</td>
                        <td class="actions" style="font-size:2em; text-align:center;vertical-align:central">
                            <a href="@Url.Action("CMSUserEdit", "CMSUsers", new { @id = @item.iCMSUserID })"><i class="fa fa-pencil"></i></a>
                            &nbsp;&nbsp;&nbsp;
                            <a id="@item.iCMSUserID" class="modal-with-zoom-anim modal-basic" href="#deleteItemModal" onclick="deleteItemConfirm(@item.iCMSUserID)"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="row">
            <hr />
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="mb-md keep-right" style="float:right;">
                    <a id="btnAddCMSUser" href="@Url.Action("CMSUserAdd", "CMSUsers")" class="btn btn-primary">Add <i class="fa fa-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
@Html.HiddenFor(Model => Model.iCMSUserID)
<!-- end: page -->

<!-- Modal Animation -->
<!-- delete modal popup -->
<div id="deleteItemModal" class="zoom-anim-dialog modal-block modal-block-primary mfp-hide">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">Are you sure?</h2>
        </header>
        <div class="panel-body">
            <div class="modal-wrapper">
                <div class="modal-icon">
                    <i class="fa fa-question-circle"></i>
                </div>
                <div class="modal-text">
                    <p>Are you sure that you want to delete this user?</p>
                </div>
            </div>
        </div>
        <footer class="panel-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-primary modal-dismiss" onclick="deleteItem()">Confirm</button>
                    <button class="btn btn-default modal-dismiss">Cancel</button>
                </div>
            </div>
        </footer>
    </section>
</div>
<!-- delete item modal popup -->

<!-- information modal popup -->
<a id="infoItemModalAnchor" style="display:none;" class="mb-xs mt-xs mr-xs modal-basic btn btn-info" href="#infoItemModal"></a>

<div id="infoItemModal" class="modal-block modal-block-info mfp-hide">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">Information</h2>
        </header>
        <div class="panel-body">
            <div class="modal-wrapper">
                <div class="modal-icon">
                    <i class="fa fa-info-circle"></i>
                </div>
                <div class="modal-text">
                    <p>There cannot be no CMS users.</p>
                </div>
            </div>
        </div>
        <footer class="panel-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-info modal-dismiss">OK</button>
                </div>
            </div>
        </footer>
    </section>
</div>
<!-- information modal popup -->

<!-- add item success -->
<script type="text/javascript">
    function addItemSuccess() {

        var notice = new PNotify({
			title: 'Click to Close',
			text: 'User added successfully.',
			type: 'success',
			addclass: 'click-2-close',
			hide: false,
			buttons: {
				closer: false,
				sticker: false
			}
		});

		notice.get().click(function() {
			notice.remove();
		});
    }
</script>

<!-- update item success -->
<script type="text/javascript">
    function updatedItemSuccess() {

        var notice = new PNotify({
			title: 'Click to Close',
			text: 'User updated successfully.',
			type: 'success',
			addclass: 'click-2-close',
			hide: false,
			buttons: {
				closer: false,
				sticker: false
			}
		});

		notice.get().click(function() {
			notice.remove();
		});
    }
</script>

<!-- delete item success -->
<script type="text/javascript">
    function deleteItemSuccess() {

        var notice = new PNotify({
			title: 'Click to Close',
			text: 'User deleted successfully.',
			type: 'success',
			addclass: 'click-2-close',
			hide: false,
			buttons: {
				closer: false,
				sticker: false
			}
		});

		notice.get().click(function() {
			notice.remove();
		});
    }
</script>

<!-- delete info item -->
<script type="text/javascript">
    function deleteInfoItem() {

        var notice = new PNotify({
			title: 'Click to Close',
			text: 'There cannot be no CMS users.',
			type: 'info',
			addclass: 'click-2-close',
			hide: false,
			buttons: {
				closer: false,
				sticker: false
			}
		});

		notice.get().click(function() {
			notice.remove();
		});
    }
</script>

<script type="text/javascript">
    function deleteItemConfirm(iItemID) {
        //SET ITEM ID TO DELETE
        $('#iCMSUserID').val(iItemID);
    }
</script>

<!-- delete item -->
<script type="text/javascript">
    function deleteItem() {

        var iCMSUserID = $('#iCMSUserID').val();

        if (iCMSUserID != 0) {
            $.ajax({
                url: '@Url.Action("CMSUserDelete", "CMSUsers")',
                type: "POST",
                data: { "iCMSUserID": iCMSUserID },
                success: function (info) {
                    // states is your JSON array
                    if (info.bIsSuccess == true) {
                        window.location.href = "/CMS/CMSUsers/CMSUsersView/";
                    }
                    else {
                        deleteInfoItem();
                    }
                }
            });
        }
    }
</script>

@**** CHANGE MASTER PAGE / LAYOUT PAGE HEADER (H2) TEXT AND PAGE TITLE AFTER PAGE LOADS ****@
@**** DISPLAY SUCCESS ON USER ADD ****@
@**** DISPLAY SUCCESS ON USER UPDATE ****@
@**** DISPLAY SUCCESS ON USER DELETE ****@
<script type="text/javascript">
    window.onload = function () {
        $("#strPageTitle").text("CMS Users | Colmart CMS");
        $("#h2PageHeader").text("CMS Users");

        //Update Breadcrumbs
        $("#olBreadcrumbs").append("<li><span>CMS Users</span></li>");

        @{
            //ADD SUCCESS NOTIFICATION
            if (TempData["bIsCMSUserAdded"] != null)
            {
                if ((bool)TempData["bIsCMSUserAdded"] == true)
                {
                    <text>
                        addItemSuccess();
                    </text>
                }
            }
            //UPDATE SUCCESS NOTIFICATION
            if (TempData["bIsCMSUserUpdated"] != null)
            {
                if ((bool)TempData["bIsCMSUserUpdated"] == true)
                {
                    <text>
                        updatedItemSuccess();
                    </text>
                }
            }
            //DELETE SUCCESS NOTIFICATION
            if (TempData["bIsCMSUserDeleted"] != null)
            {
                if ((bool)TempData["bIsCMSUserDeleted"] == true)
                {
                    <text>
                        deleteItemSuccess();
                    </text>
                }
            }
        }
    }
</script>